/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};

/* dynamics:(i0[7],i1[4])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6;
  /* #0: @0 = input[1][3] */
  w0 = arg[1] ? arg[1][3] : 0;
  /* #1: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #5: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #6: @2 = (@2*@4) */
  w2 *= w4;
  /* #7: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #8: @4 = cos(@1) */
  w4 = cos( w1 );
  /* #9: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #10: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #11: @4 = (@4*@3) */
  w4 *= w3;
  /* #12: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #13: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #14: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #15: @3 = (-@1) */
  w3 = (- w1 );
  /* #16: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #17: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #18: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  /* #19: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #20: output[0][4] = @3 */
  if (res[0]) res[0][4] = w3;
  /* #21: @3 = input[1][2] */
  w3 = arg[1] ? arg[1][2] : 0;
  /* #22: @5 = 9.81 */
  w5 = 9.8100000000000005e+00;
  /* #23: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #24: @6 = tan(@6) */
  w6 = tan( w6 );
  /* #25: @6 = (@6/@0) */
  w6 /= w0;
  /* #26: @5 = (@5*@6) */
  w5 *= w6;
  /* #27: @3 = (@3+@5) */
  w3 += w5;
  /* #28: output[0][5] = @3 */
  if (res[0]) res[0][5] = w3;
  /* #29: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #30: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #31: @2 = (@2+@4) */
  w2 += w4;
  /* #32: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #33: @2 = (@2+@1) */
  w2 += w1;
  /* #34: @2 = sqrt(@2) */
  w2 = sqrt( w2 );
  /* #35: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 7;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
